#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 1052-web-01 34.74.235.186
	server 1052-web-02 35.237.233.88" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
